In [1]:
# cloning GitHub Repo
!git clone https://github.com/chase-kusterer/BASD.git

# changing directory
import os
repo_name = '/content/BASD/'
os.chdir(repo_name)

# checking results
print(f"Current working directory changed to: {os.getcwd()}")

Cloning into 'BASD'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 53 (delta 15), reused 38 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (53/53), 5.20 MiB | 18.36 MiB/s, done.
Resolving deltas: 100% (15/15), done.
Current working directory changed to: /content/BASD

<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />

<br><h1>Structured Data in Python</h1>
DAT-7470 - Business Analysis with Structured Data<br>
Guided Analysis Notebook<br><br>

Written by Chase Kusterer - Faculty of Analytics <br>
Hult International Business School <br>
<a href="https://chase-kusterer.github.io/">https://chase-kusterer.github.io/</a> <br><br><br><br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<br>
<h2>Part 1: Importing Excel Data into Python</h2>
Earlier, we learned several useful techniques related to operating on lists. <strong>DataFrames</strong>, which resemble Excel spreadsheets, are slightly more complicated as unlike lists, they are multidimensional. In other words, lists can be thought of as a single row of data, whereas <strong>DataFrames</strong> consist of rows and columns. There are hundreds of DataFrame methods, which can be found in the official  <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html">Python documentation</a>.
<br><br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<h3>The Two Month's Salary Challenge</h3><br>
The content of this chapter is reliant on a simple yet elegant dataset. This dataset has been published in <a href="https://www.amazon.com/Marketing-Data-Science-Techniques-Predictive/dp/0133886557">Marketing Data Science - Modeling Techniques in Predictive Analytics with R and Python</a>, written by Dr. Thomas Miller of Northwestern University. As such, it is fitting to allow Dr. Miller to introduce this dataset, as well as the two month's salary challenge:
<br>
<p><em>I never understood why giving a diamond was the social norm when proposing
marriage. As I began searching for an engagement ring, two thoughts
kept racing through my mind: “How will I be able to find the right diamond?”
and “What is this thing going to cost me?” It goes without saying
that my fianc´ee-to-be is worth the expense, but very seldom in our lives do
    we spend two month’s salary on a product we know so little about. </em><a href="./documents/miller_mds_two_months_salary_case.pdf">Click here to continue reading</a>.</p>
<br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />

<strong>a) Basic Import of Excel Data</strong><br>
The <em>pandas</em> package has an excellent method to help us import Excel-style data into Python. This method, <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html">read_excel(&nbsp;)</a>, has a number of optional arguments designed to make our lives easier. To begin, let's import <em>pandas</em> as <em>pd</em> and then read in the dataset with <strong>pd.read_excel(&nbsp;)</strong>.
<br><br>
The steps for this process are as follows:<br>
<font>
&emsp;1. Import <em>pandas</em>.<br>
&emsp;2. Specify the location of the data.*<br>
&emsp;3. Use read_excel(&nbsp;) to read in the data.</font>

<font>*The Excel file should be stored in the same place as this Jupyter notebook.</font>

In [4]:
# Step 1: importing pandas
import pandas as pd
import warnings

# suppressing user warnings
warnings.filterwarnings("ignore", category=UserWarning)


# Step 2: storing the path to the dataset
file = "./datasets/diamonds.xlsx"


# Step 3: reading the file into Python through pandas
diamonds = pd.read_excel(io = file)

# Step 4 (optional): checking results
diamonds.head(n = 5)

   Obs  carat  color  clarity  cut  channel  store  price
0    1   0.32      3        7    0        0      7   1375
1    2   0.35      5        7    1        0      7   1680
2    3   0.40      4        7    1        0      7   2245
3    4   0.59      5        7    0        0      3   2495
4    5   0.72      7        8    0        0      8   2699

<br><hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<h3>Bad Practice: Data Dumping</h3><br>
The <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html">.head(&nbsp;) method</a> is used to display the first <em>n</em> rows of a dataset. This is important, because as you know from the required reading for this session:<br><br>
<div align="center"><strong><font style="color:red;">Attempting to view an entire dataset is a bad idea.</font></strong></div><br>
When we attempted to view the entire dataset in <em>Session 11.1.2</em>, our view was automatically restricted to the first and last five rows of the dataset. This is panda's way of preventing us from unintentionally running something that might be process intense, and that we most likely will never use for any analytical endeavors.
<br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>

<strong>b) Use <em>head(&nbsp;)</em> to view the top <em>n</em> rows of the diamonds dataframe.</strong>

In [5]:
# viewing the first n rows of diamonds
diamonds.head(n = 5)

   Obs  carat  color  clarity  cut  channel  store  price
0    1   0.32      3        7    0        0      7   1375
1    2   0.35      5        7    1        0      7   1680
2    3   0.40      4        7    1        0      7   2245
3    4   0.59      5        7    0        0      3   2495
4    5   0.72      7        8    0        0      8   2699

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h2>Part II: Slicing DataFrames</h2><br>
Columns can be sliced in a similar fashion to how list items are indexed:
<br><br>

~~~
# slicing a single column
DataFrame['feature name']
~~~

<br>
This is exemplified in the code below.

In [6]:
# slicing the carat column (type will be pd.Series)
diamonds['carat'].head(n = 5)

0    0.32
1    0.35
2    0.40
3    0.59
4    0.72
Name: carat, dtype: float64

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>

For Python, the output of the code above is easy and efficient to read. If we were using the <em>carat</em> column as an input for another operation, this is the way to go. For humans, however, it would be beneficial to output this as a table. One advantage of Jupyter Notebook is that it will automatically output an html table if it is provided with a DataFrame.

In [7]:
# slicing the carat column (type will be pd.DataFrame)
diamonds[  ['carat']  ].head(n = 5)

   carat
0   0.32
1   0.35
2   0.40
3   0.59
4   0.72

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br><br>
The codes below have been designed to further exemplify the behind the scenes type conversion.

In [8]:
# checking data type
type(diamonds['carat'])

pandas.core.series.Series

In [9]:
# checking data type
type(diamonds[    ['carat']    ])

pandas.core.frame.DataFrame

<br><hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
We can also slice multiple features, as in the code below.

In [10]:
# slicing multiple columns
diamonds[  ['carat', 'color', 'clarity', 'cut']  ].head(n = 5)

   carat  color  clarity  cut
0   0.32      3        7    0
1   0.35      5        7    1
2   0.40      4        7    1
3   0.59      5        7    0
4   0.72      7        8    0

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h2>Part III: Conditional Subsetting</h2><br>
DataFrames can be filtered using conditions as in the following code. In human language, the code below can be interpreted as follows: "Give me all of the diamonds that have a carat weight greater than two."

In [ ]:
# carat where carat is greater than 2
diamonds[ (diamonds['carat'] > 2) ]

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
Conditional subsetting can be extended by simply adding more conditions on to end of a line of code.
<br><br>

In [ ]:
# filtering feature qualities
diamonds[ (diamonds['carat']   <= 1) ]\
        [ (diamonds['color']   >= 2) ]\
        [ (diamonds['clarity'] == 3) ]\
        [ (diamonds['cut']     != 1) ]

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
This can get messy very quickly. In many cases, it is easier to develop the code one step at a time to help keep things organized.

In [ ]:
# data to be subset
data = diamonds[ ['carat', 'color', 'clarity', 'cut'] ]


# conditions
carat_condition   = (diamonds['carat']   <= 1) # carat
color_condition   = (diamonds['color']   >= 2) # color
clarity_condition = (diamonds['clarity'] == 3) # clarity
cut_condition     = (diamonds['cut']     != 1) # cut


# putting it all together
data[carat_condition][color_condition][clarity_condition][cut_condition]

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>
<h2>Part IV: Case Study - Finding the "Best" Diamond on a Budget</h2><br>
<strong>Your goal in this case study is to find the "best" five diamond engagement rings for a "normal" Chicago citizen.</strong> To help you along the way, below is some domain knowledge on income in the city of Chicago during the data collection period.
<br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<strong>Foundational Domain Knowledge</strong><br>
The diamond data was collected in the city of Chicago in 2007. During this time, per capita income for the city of Chicago was approximately \&#36;34,775, according to <a href="https://www.census.gov/">the U.S. Census Bureau website</a>. Following the "two month's salary" rule, a "normal" Chicago citizen would have a budget of approximately \&#36;5,795 to spend on a diamond engagement ring.
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<br>
Use the open coding block below to conditionally subset price, carat, color, clarity, and cut to find the "best" diamond engagement ring given this budget. You may define "best" in any way you please, as long as you can reasonably justify your rationale (use the markdown cell below for this).

Open this markdown cell to explain the rationale for your selection criteria. Aim for at least 100 words.

In [ ]:
# don't forget to add comments to your code!

<hr style="height:.9px;border:none;color:#333;background-color:#333;" /><br>

~~~

 __ _             _   _                           _   
/ _\ |_ __ _ _ __| |_(_)_ __   __ _    ___  _   _| |_
\ \| __/ _` | '__| __| | '_ \ / _` |  / _ \| | | | __|
_\ \ || (_| | |  | |_| | | | | (_| | | (_) | |_| | |_
\__/\__\__,_|_|   \__|_|_| |_|\__, |  \___/ \__,_|\__|
                              |___/                   
 __  _____  __    ___    __  ___   _                  
/ _\/__   \/__\  /___\/\ \ \/ _ \ / \                 
\ \   / /\/ \// //  //  \/ / /_\//  /                 
_\ \ / / / _  \/ \_// /\  / /_\\/\_/                  
\__/ \/  \/ \_/\___/\_\ \/\____/\/                    
                                                      

~~~

<br>